package UIVentana;

import Distribuciones.Poisson;
import Logica.Estado;
import Logica.Simular;
import Logica.SimularB;
import Logica.Solicitante;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucho
 */
public class Principal extends javax.swing.JFrame {

    private static final String ALTERNATIVA_A = "Alternativa A";
    private static final String ALTERNATIVA_B = "Alternativa B";

    private Object[] filaAnteriorA = new Object[20];
    private Object[] filaNuevaA = new Object[20];
    private Object[] filaAnteriorB = new Object[17];
    private Object[] filaNuevaB = new Object[17];
    private Float reloj;
    private Integer cantidadSimulaciones;

    private Integer mediaFormulario = 0;

    public Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Simular = new javax.swing.JButton();
        cb_alternativas = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        tx_llegada = new javax.swing.JTextField();
        tx_atencionA_a = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbl_atencionA = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tx_llenarFormulario = new javax.swing.JTextField();
        tx_atencionA_b = new javax.swing.JTextField();
        lbl_atencionB = new javax.swing.JLabel();
        tx_atencionB = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_tiempo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_desde = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_hasta = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tx_promedioA = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tx_atendidosA = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        tiempoSimulacionA = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tx_atendidosB = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tx_promedioB = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        tiempoSimulacionB = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        principalA = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_solicitantesA = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb_solicitantesB = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        principalB = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Simular.setText("Simular");
        btn_Simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimularActionPerformed(evt);
            }
        });

        cb_alternativas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alternativa A", "Alternativa B" }));
        cb_alternativas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_alternativasActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Variables Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        tx_llegada.setText("0.15");
        tx_llegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_llegadaActionPerformed(evt);
            }
        });

        tx_atencionA_a.setText("6");
        tx_atencionA_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_atencionA_aActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Llegada Solicitante (poisson)");

        lbl_atencionA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_atencionA.setText("Atencion empleado (uniforme)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Llenar Formulario (exponencial)");

        tx_llenarFormulario.setText("59");
        tx_llenarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_llenarFormularioActionPerformed(evt);
            }
        });

        tx_atencionA_b.setText("9");
        tx_atencionA_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_atencionA_bActionPerformed(evt);
            }
        });

        lbl_atencionB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_atencionB.setText("Atencion empleado (exponencial)");

        tx_atencionB.setText("27");
        tx_atencionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_atencionBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_atencionA)
                    .addComponent(jLabel11)
                    .addComponent(lbl_atencionB)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tx_llenarFormulario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tx_llegada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(tx_atencionA_a, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tx_atencionB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(tx_atencionA_b, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tx_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tx_llenarFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_atencionA)
                    .addComponent(tx_atencionA_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_atencionA_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_atencionB)
                    .addComponent(tx_atencionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atención Oficina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tiempo Total:");

        txt_tiempo.setText("100");
        txt_tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tiempoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mostrar Desde:");

        txt_desde.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mostrar Hasta:");

        txt_hasta.setText("100");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salidas Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alternativa A", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Solicitantes Atendidos: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Promedio Tiempo Atencion:");

        tx_promedioA.setEnabled(false);
        jScrollPane2.setViewportView(tx_promedioA);

        tx_atendidosA.setEnabled(false);
        jScrollPane3.setViewportView(tx_atendidosA);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tiempo Simulacion:");

        tiempoSimulacionA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tiempoSimulacionA, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tiempoSimulacionA, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alternativa B", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Solicitantes Atendidos: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Promedio Tiempo Atencion:");

        tx_atendidosB.setEnabled(false);
        jScrollPane6.setViewportView(tx_atendidosB);

        tx_promedioB.setEnabled(false);
        jScrollPane4.setViewportView(tx_promedioB);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Tiempo Simulacion:");

        tiempoSimulacionB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tiempoSimulacionB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tiempoSimulacionB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        principalA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reloj", "Evento", "Tiempo Llegada", "Proxima Llegada", "RND", "Tiempo Formulario", "Fin Formulario", "RND", "Tiempo Atencion", "Fin Atencion 1", "Estado  1", "Fin Atencion 2", "Estado 2", "Fin Atencion 3", " Estado 3", "Fin Atencion 4", "Estado  4", "Cola", "Acum Solicitantes", "Ac. Tiemp. Solic. Sist."
            }
        ));
        principalA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(principalA);

        tb_solicitantesA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reloj"
            }
        ));
        tb_solicitantesA.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(tb_solicitantesA);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1697, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alternativa A", jPanel6);

        tb_solicitantesB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reloj"
            }
        ));
        tb_solicitantesB.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane7.setViewportView(tb_solicitantesB);

        principalB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reloj", "Evento", "Tiempo Llegada", "Proxima Llegada", "RND", "Tiempo Atencion", "Fin Atencion 1", "Estado Empleado 1", "Fin Atencion 2", "Estado Empleado 2", "Fin Atencion 3", " Estado Empleado 3", "Fin Atencion 4", "Estado Empleado 4", "Cola", "Acum Solicitantes", "Ac. Tiempo Soli. Sist."
            }
        ));
        principalB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalBMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(principalB);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1697, Short.MAX_VALUE)
                    .addComponent(jScrollPane8))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alternativa B", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Simular, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cb_alternativas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_alternativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Simular)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimularActionPerformed
        this.reloj = 0.0f;
        this.cantidadSimulaciones = 0;
        Double tiempoSimular = Double.parseDouble(this.txt_tiempo.getText());
        Float desde = Float.parseFloat(this.txt_desde.getText());
        Float hasta = Float.parseFloat(this.txt_hasta.getText());
        Double mediaPoissonLlegada = Double.parseDouble(this.tx_llegada.getText());
        Double mediaExpLlenarForm = Double.parseDouble(this.tx_llenarFormulario.getText());
        Integer unifAtencionA = Integer.parseInt(this.tx_atencionA_a.getText());
        Integer unifAtencionB = Integer.parseInt(this.tx_atencionA_b.getText());
        Double mediaExpAtencionB = Double.parseDouble(this.tx_atencionB.getText());

        if (this.cb_alternativas.getSelectedItem().equals(Principal.ALTERNATIVA_A)) {
            simularAlternativaA(mediaPoissonLlegada, mediaExpLlenarForm,
                    unifAtencionA, unifAtencionB, tiempoSimular, desde, hasta);
        } else {
            simularAlternativaB(mediaPoissonLlegada,mediaExpAtencionB,tiempoSimular,
                    desde,hasta);
        }

        // this.txt_promedio.setText(new DecimalFormat("0.00").format(simular.obtenerPromedioPermanencia()));

    }//GEN-LAST:event_btn_SimularActionPerformed

    private void tx_atencionA_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_atencionA_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_atencionA_aActionPerformed

    private void tx_llegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_llegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_llegadaActionPerformed

    private void txt_tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tiempoActionPerformed

    private void cb_alternativasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_alternativasActionPerformed

        if (this.cb_alternativas.getSelectedItem().equals("Alternativa A")) {
            this.lbl_atencionA.enable();
            this.tx_atencionA_a.enable();
            this.tx_llenarFormulario.enable();
            this.tx_atencionA_b.enable();
            this.lbl_atencionB.disable();
            this.tx_atencionB.disable();
        }
        if (this.cb_alternativas.getSelectedItem().equals("Alternativa B")) {
            this.lbl_atencionB.enable();
            this.tx_atencionB.enable();
            this.tx_llenarFormulario.disable();
            this.lbl_atencionA.disable();
            this.tx_atencionA_a.disable();
            this.tx_atencionA_b.disable();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cb_alternativasActionPerformed

    private void tx_llenarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_llenarFormularioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_llenarFormularioActionPerformed

    private void tx_atencionA_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_atencionA_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_atencionA_bActionPerformed

    private void tx_atencionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_atencionBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_atencionBActionPerformed

    private void principalAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalAMouseClicked

        int[] selected = this.principalA.getSelectedRows();
        for (int i = 0; i < selected.length; i++) {
            this.tb_solicitantesA.setRowSelectionAllowed(true);

        }

    }//GEN-LAST:event_principalAMouseClicked

    private void principalBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_principalBMouseClicked

    private void inicializarFilaA() {
        this.filaAnteriorA[0] = 0.0f; // Reloj
        this.filaAnteriorA[1] = "-"; //Evento
        this.filaAnteriorA[2] = Poisson.variableAleatoria(Double.parseDouble(this.tx_llegada.getText())); //Tiempo Llegada
        this.filaAnteriorA[3] = this.filaAnteriorA[2];//Proxima Llegada.
        this.filaAnteriorA[4] = "-"; //RND
        this.filaAnteriorA[5] = "-"; // Tiempo Formulario
        this.filaAnteriorA[6] = "-"; // Fin Formulario
        this.filaAnteriorA[7] = "-"; //RND
        this.filaAnteriorA[8] = "-"; //tiempo Atencion
        this.filaAnteriorA[9] = "-";//Fin Atencion;
        this.filaAnteriorA[10] = "LIBRE"; // Estado
        this.filaAnteriorA[11] = "-";//Fin Atencion;
        this.filaAnteriorA[12] = "LIBRE"; // Estado
        this.filaAnteriorA[13] = "-";//Fin Atencion;
        this.filaAnteriorA[14] = "LIBRE"; // Estado
        this.filaAnteriorA[15] = "-";//Fin Atencion;
        this.filaAnteriorA[16] = "LIBRE"; // Estado
        this.filaAnteriorA[17] = (Integer) 0;  //Cola
        this.filaAnteriorA[18] = (Integer) 0; // Acumulador Solicitantes
        this.filaAnteriorA[19] = 0.0f; // tiempo en sistema
    }

    private void inicializarFilaB() {
        this.filaAnteriorB[0] = 0.0f; // Reloj
        this.filaAnteriorB[1] = "-"; //Evento
        this.filaAnteriorB[2] = Poisson.variableAleatoria(Double.parseDouble(this.tx_llegada.getText())); //Tiempo Llegada
        this.filaAnteriorB[3] = this.filaAnteriorB[2];//Proxima Llegada.
        this.filaAnteriorB[4] = "-"; //RND
        this.filaAnteriorB[5] = "-"; //tiempo Atencion
        this.filaAnteriorB[6] = "-";//Fin Atencion;
        this.filaAnteriorB[7] = "LIBRE"; // Estado
        this.filaAnteriorB[8] = "-";//Fin Atencion;
        this.filaAnteriorB[9] = "LIBRE"; // Estado
        this.filaAnteriorB[10] = "-";//Fin Atencion;
        this.filaAnteriorB[11] = "LIBRE"; // Estado
        this.filaAnteriorB[12] = "-";//Fin Atencion;
        this.filaAnteriorB[13] = "LIBRE"; // Estado
        this.filaAnteriorB[14] = (Integer) 0;  //Cola
        this.filaAnteriorB[15] = (Integer) 0; // Acumulador Solicitantes
        this.filaAnteriorB[16] = 0.0f; // tiempo en sistema
    }

    private void setearFilaAnterior(Object[] filaAnterior, Object[] filaNueva) {
        for (int i = 0; i < filaAnterior.length; i++) {
            filaAnterior[i] = filaNueva[i];
        }
    }

    private void crearColumnasClientesA(Simular simular, DefaultTableModel modelo2) {

        modelo2 = (DefaultTableModel) this.tb_solicitantesA.getModel();
        Integer cantidad = simular.obtenerSolicitantes().size();
        for (int i = 0; i < cantidad; i++) {
            if (!estaClienteEnColumna(modelo2, simular.obtenerSolicitantes().get(i))) {
                Integer n = simular.obtenerSolicitantes().get(i).getNumero();
                modelo2.addColumn("Estado [" + n + "]");
                modelo2.addColumn("Hora Llegada [" + n + "]");
                modelo2.addColumn("Hora Salida [" + n + "]");
            }

        }
        this.tb_solicitantesA.setModel(modelo2);
    }
//    private Integer obtenerPosicionInicial(DefaultTableModel modelo, Integer k) {
//        Integer pos = 0;
//        for (int i = 0; i < modelo.getColumnCount(); i += 4) {
//            String nombreCol = modelo.getColumnName(i);
//            if (obtenerKdeColumna(nombreCol).equals(k)) {
//                pos = i;
//                break;
//            }
//        }
//        return pos;
//    }

    private boolean estaClienteEnColumna(DefaultTableModel modelo2, Solicitante solicitante) {
        for (int i = 1; i < modelo2.getColumnCount(); i += 3) {
            String nombreColumna = modelo2.getColumnName(i);
            Integer nroSolicitante = obtenerNumeroSolicitanteColumna(nombreColumna);
            if (solicitante.getNumero().equals(nroSolicitante)) {
                return true;
            }

        }
        return false;
    }

    private void llenarFilaSolicitantesA(Simular simular, DefaultTableModel modelo2) {
        ArrayList<Solicitante> solicitantes = simular.obtenerSolicitantes();
        modelo2 = (DefaultTableModel) this.tb_solicitantesA.getModel();
        Object[] filaClientes = new Object[modelo2.getColumnCount()];
        filaClientes[0] = this.reloj;
        for (int i = 1; i < modelo2.getColumnCount(); i += 3) {
            String nombreColumna = modelo2.getColumnName(i);
            Integer numeroCliente = obtenerNumeroSolicitanteColumna(nombreColumna);
            for (int j = 0; j < solicitantes.size(); j++) {
                if (solicitantes.get(j).getNumero().equals(numeroCliente)) {
                    filaClientes[i] = solicitantes.get(j).getEstado();
                    filaClientes[i + 1] = solicitantes.get(j).getHoraLlegada();
                    if (solicitantes.get(j).getEstado().equals(Estado.FUERA_SISTEMA)) {
                        filaClientes[i + 2] = solicitantes.get(j).getHoraSalida();
                    }
                }
            }
        }
        modelo2.addRow(filaClientes);
        this.tb_solicitantesA.setModel(modelo2);
    }

    private Integer obtenerNumeroSolicitanteColumna(String nombreColumna) {
        String numero = "";
        for (int i = 0; i < nombreColumna.length(); i++) {
            if (Character.isDigit(nombreColumna.charAt(i))) {
                numero = numero.concat(nombreColumna.substring(i, i + 1));
            }
        }
        return Integer.parseInt(numero);
    }

//    private void mostrarEnTablaPrincipal(DefaultTableModel modelo) {
//        modelo.addRow(crearArregloFilaPrincipal());
//    }
//    private Object[] crearArregloFilaPrincipal() {
//        Object[] retorno = new Object[this.filaNueva.size()];
//        for (int i = 0; i < retorno.length; i++) {
//            retorno[i] = this.filaNueva.get(i);
//        }
//        return retorno;
//    }
//    private Object[] crearArregloFilaClientes() {
//        Object[] retorno = new Object[this.filaClientes.size() + 1];
//        retorno[0] = this.filaNueva.get(0);
//        for (int i = 1; i < retorno.length; i++) {
//            retorno[i] = this.filaClientes.get(i);
//        }
//        return retorno;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Simular;
    private javax.swing.JComboBox<String> cb_alternativas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_atencionA;
    private javax.swing.JLabel lbl_atencionB;
    private javax.swing.JTable principalA;
    private javax.swing.JTable principalB;
    private javax.swing.JTable tb_solicitantesA;
    private javax.swing.JTable tb_solicitantesB;
    private javax.swing.JLabel tiempoSimulacionA;
    private javax.swing.JLabel tiempoSimulacionB;
    private javax.swing.JTextField tx_atencionA_a;
    private javax.swing.JTextField tx_atencionA_b;
    private javax.swing.JTextField tx_atencionB;
    private javax.swing.JTextPane tx_atendidosA;
    private javax.swing.JTextPane tx_atendidosB;
    private javax.swing.JTextField tx_llegada;
    private javax.swing.JTextField tx_llenarFormulario;
    private javax.swing.JTextPane tx_promedioA;
    private javax.swing.JTextPane tx_promedioB;
    private javax.swing.JTextField txt_desde;
    private javax.swing.JTextField txt_hasta;
    private javax.swing.JTextField txt_tiempo;
    // End of variables declaration//GEN-END:variables

    private void simularAlternativaA(Double mediaPoissonLlegada, Double mediaExpLlenarForm,
            Integer unifAtencionA, Integer unifAtencionB, Double tiempoSimular, Float desde, Float hasta) {

        Simular simular = new Simular(mediaPoissonLlegada, mediaExpLlenarForm,
                unifAtencionA, unifAtencionB);

        inicializarFilaA();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) this.principalA.getModel();
        modelo.setRowCount(0);
        DefaultTableModel modeloCliente = new DefaultTableModel();
        modeloCliente = (DefaultTableModel) this.tb_solicitantesA.getModel();
        modeloCliente.setRowCount(0);
        modeloCliente.setColumnCount(1);
        modelo.addRow(this.filaAnteriorA);
        while (this.reloj <= tiempoSimular) {
            this.filaNuevaA = simular.simularA(this.filaAnteriorA);
            this.reloj = (Float) this.filaNuevaA[0];

            if (this.reloj >= desde && this.reloj <= hasta) {
                modelo.addRow(this.filaNuevaA);
                crearColumnasClientesA(simular, modeloCliente);
                llenarFilaSolicitantesA(simular, modeloCliente);
            }

            // this.columnasReplicadas = simular.getNroCliente() + 1;
//        mostrarEnTablaClientes();
            this.cantidadSimulaciones++;
            setearFilaAnterior(this.filaAnteriorA, this.filaNuevaA);
            //   crearTablaEcuacionDiferencial(simular, modeloEcDif);
        }
        
        this.tx_atendidosA.setText(((Integer)this.filaNuevaA[18]).toString());
        this.tx_promedioA.setText(""+((Float) this.filaNuevaA[19] / (Integer) this.filaNuevaA[18]));
        
    }

    private void simularAlternativaB(Double mediaPoissonLlegada, Double mediaAtencion,
            Double tiempoSimular,Float desde,Float hasta) {
        SimularB simular = new SimularB(mediaPoissonLlegada,mediaAtencion);
        inicializarFilaB();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) this.principalB.getModel();
        modelo.setRowCount(0);
        DefaultTableModel modeloCliente = new DefaultTableModel();
        modeloCliente = (DefaultTableModel) this.tb_solicitantesB.getModel();
        modeloCliente.setRowCount(0);
        modeloCliente.setColumnCount(1);
        modelo.addRow(this.filaAnteriorB);
        while (this.reloj <= tiempoSimular) {
            this.filaNuevaB = simular.simularB(this.filaAnteriorB);
            this.reloj = (Float) this.filaNuevaB[0];

            if (this.reloj >= desde && this.reloj <= hasta) {
                modelo.addRow(this.filaNuevaB);
                crearColumnasClientesB(simular, modeloCliente);
                llenarFilaSolicitantesB(simular, modeloCliente);
            }

            // this.columnasReplicadas = simular.getNroCliente() + 1;
//        mostrarEnTablaClientes();
            this.cantidadSimulaciones++;
            setearFilaAnterior(this.filaAnteriorB, this.filaNuevaB);
            //   crearTablaEcuacionDiferencial(simular, modeloEcDif);
        }
        
        this.tx_atendidosB.setText(((Integer)this.filaNuevaB[15]).toString());
        this.tx_promedioB.setText(""+((Float) this.filaNuevaB[16] / (Integer) this.filaNuevaB[15]));
    }

    private void crearColumnasClientesB(SimularB simular, DefaultTableModel modelo2) {

        modelo2 = (DefaultTableModel) this.tb_solicitantesB.getModel();
        Integer cantidad = simular.obtenerSolicitantes().size();
        for (int i = 0; i < cantidad; i++) {
            if (!estaClienteEnColumna(modelo2, simular.obtenerSolicitantes().get(i))) {
                Integer n = simular.obtenerSolicitantes().get(i).getNumero();
                modelo2.addColumn("Estado [" + n + "]");
                modelo2.addColumn("Hora Llegada [" + n + "]");
                modelo2.addColumn("Hora Salida [" + n + "]");
            }

        }
        this.tb_solicitantesB.setModel(modelo2);
    }

    private void llenarFilaSolicitantesB(SimularB simular, DefaultTableModel modelo2) {
        ArrayList<Solicitante> solicitantes = simular.obtenerSolicitantes();
        modelo2 = (DefaultTableModel) this.tb_solicitantesB.getModel();
        Object[] filaClientes = new Object[modelo2.getColumnCount()];
        filaClientes[0] = this.reloj;
        for (int i = 1; i < modelo2.getColumnCount(); i += 3) {
            String nombreColumna = modelo2.getColumnName(i);
            Integer numeroCliente = obtenerNumeroSolicitanteColumna(nombreColumna);
            for (int j = 0; j < solicitantes.size(); j++) {
                if (solicitantes.get(j).getNumero().equals(numeroCliente)) {
                    filaClientes[i] = solicitantes.get(j).getEstado();
                    filaClientes[i + 1] = solicitantes.get(j).getHoraLlegada();
                    if (solicitantes.get(j).getEstado().equals(Estado.FUERA_SISTEMA)) {
                        filaClientes[i + 2] = solicitantes.get(j).getHoraSalida();
                    }
                }
            }
        }
        modelo2.addRow(filaClientes);
        this.tb_solicitantesB.setModel(modelo2);
    }
}
